[package]
name = "kentiers/anvil"
version = "0.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
license = "MIT"
authors = ["kentiers"]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
