[package]
name = "kentiers/anvil-consumer-smoke"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
license = "MIT"
private = true

[server-dependencies]
Anvil = "kentiers/anvil@0.1.1"
