name: Verify

on:
  push:
    branches: [main]
  pull_request:

jobs:
  verify:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rokit
        shell: pwsh
        run: |
          Invoke-RestMethod https://raw.githubusercontent.com/rojo-rbx/rokit/main/scripts/install.ps1 | Invoke-Expression
          $env:PATH = "$HOME\.rokit\bin;$env:PATH"
          "$HOME\.rokit\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          rokit trust rojo-rbx/rojo UpliftGames/wally JohnnyMorganz/luau-lsp JohnnyMorganz/stylua Kampfkarren/selene rojo-rbx/run-in-roblox
          rokit install


      - name: Install test dependency
        shell: pwsh
        run: wally install

      - name: Check formatting
        shell: pwsh
        run: stylua --check src/ test/ tools/ benchmarks/

      - name: Lint
        shell: pwsh
        run: selene src/ test/ tools/ benchmarks/

      - name: Type-check
        shell: pwsh
        run: |
          rojo sourcemap test.project.json --output sourcemap.json
          luau-lsp analyze --sourcemap sourcemap.json src/ test/ tools/ benchmarks/
